version: '3.9'

services:
  db:
    image: postgres:13
    container_name: lab_03_postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "${SPRING_DATASOURCE_PORT}:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATASOURCE_DBNAME}
    networks:
      - moeda_estudantil

volumes:
  postgres_data:

networks:
  moeda_estudantil:
