@startuml
left to right direction

actor "Aluno" as Aluno
actor "Professor" as Professor
actor "Empresa Parceira" as Empresa
actor "Sistema" as Sistema

usecase "Cadastrar Aluno" as CadastrarAluno
usecase "Autenticar no Sistema" as Autenticar
usecase "Resgatar Vantagens" as ResgatarVantagens
usecase "Consultar Saldo e Transações" as ConsultarSaldoAluno
usecase "Enviar Moedas para Aluno" as EnviarMoedas
usecase "Cadastrar Empresa" as CadastrarEmpresa
usecase "Cadastrar Vantagens" as CadastrarVantagens
usecase "Consultar Saldo e Transações (Professor)" as ConsultarSaldoProfessor
usecase "Enviar Notificação de Moedas para Aluno" as EnviarNotificacaoMoedas
usecase "Enviar Notificação de Cupom para Empresa e Aluno" as EnviarNotificacaoCupom
usecase "Selecionar Instituição de Ensino" as SelecionarInstituicao

Aluno --> CadastrarAluno
Aluno --> Autenticar
Aluno --> ResgatarVantagens
Aluno --> ConsultarSaldoAluno
Aluno --> SelecionarInstituicao

Professor --> EnviarMoedas
Professor --> ConsultarSaldoProfessor
Professor --> Autenticar

Empresa --> CadastrarEmpresa
Empresa --> CadastrarVantagens
Empresa --> Autenticar

Sistema --> EnviarNotificacaoMoedas
Sistema --> EnviarNotificacaoCupom
@enduml
