@startuml

actor "Aluno" as aluno
actor "Professor" as professor
actor "Empresario Parceiro" as empresario

usecase "Cadastrar Informações" as CadastrarInfo
usecase "Resgatar Vantagens" as ResgatarVantagens
usecase "Consultar Saldo e Transações" as ConsultarSaldo
usecase "Enviar Moedas" as EnviarMoedas
usecase "Cadastrar Empresa" as CadastrarEmpresa
usecase "Cadastrar Vantagens" as CadastrarVantagens
usecase "Enviar Notificação de Moedas" as EnviarNotificacaoMoedas
usecase "Enviar Notificação de Cupom" as EnviarNotificacaoCupom
usecase "Gerar cupom"as GerarCupom

aluno -- CadastrarInfo
aluno -- ResgatarVantagens
aluno -- ConsultarSaldo

professor -- EnviarMoedas
professor -- ConsultarSaldo

empresario -- CadastrarEmpresa
empresario -- CadastrarVantagens

EnviarMoedas ..> EnviarNotificacaoMoedas : <<include>>
ResgatarVantagens ..> GerarCupom : <<include>>
GerarCupom ..> EnviarNotificacaoCupom : <<include>>

@enduml